### ISSUE TITLE
Empty reply from server for long latency request (> 2 mins)

### ISSUE THREAD

**Issue by Eido95** [mockoon/mockoon#258]
**Describe the bug**
Server closes connection (with empty reply) when request reaching 2 mins latency, even though route latency was set to be **above** 2 minutes.

**To Reproduce**
* No special configurations were set.
1. Go to "Demo users API" environment
2. Select `/users` `GET` route, set route specific latency to be 2 minutes and 30 seconds (=150000 milliseconds).
3. Start server.
4. Send `GET` request to `http://localhost:2500/users`.

**Actual behavior**
```
16:31:13.101 fetch("http://localhost:2500/users")
16:31:13.122 Promise {<pending>}
16:33:13.116 VM247:1 GET http://localhost:2500/users net::ERR_EMPTY_RESPONSE
```
```
curl -v --trace-time http://localhost:2500/users
16:30:05.987863 *   Trying 127.0.0.1...
16:30:05.987958 * TCP_NODELAY set
16:30:05.988077 * Connected to localhost (127.0.0.1) port 2500 (#0)
16:30:05.988115 > GET /users HTTP/1.1
16:30:05.988115 > Host: localhost:2500
16:30:05.988115 > User-Agent: curl/7.58.0
16:30:05.988115 > Accept: */*
16:30:05.988115 > 
16:32:05.992077 * Empty reply from server
16:32:05.992373 * Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```
**Expected behavior**
```
curl -v --trace-time http://localhost:2500/users
16:58:01.710918 *   Trying 127.0.0.1...
16:58:01.711085 * TCP_NODELAY set
16:58:01.711341 * Connected to localhost (127.0.0.1) port 2500 (#0)
16:58:01.711501 > GET /users HTTP/1.1
16:58:01.711501 > Host: localhost:2500
16:58:01.711501 > User-Agent: curl/7.58.0
16:58:01.711501 > Accept: */*
16:58:01.711501 > 
16:58:01.770340 < HTTP/1.1 200 OK
16:58:01.770491 < X-Powered-By: Express
16:58:01.770627 < Content-Type: application/json; charset=utf-8
16:58:01.770782 < Content-Length: 156
16:58:01.770916 < ETag: W/"9c-/XXxN30UzQ9rDydB/h9gViUiT0o"
16:58:01.771055 < Date: Thu, 27 Feb 2020 14:58:01 GMT
16:58:01.771206 < Connection: keep-alive
16:58:01.771340 < 
16:58:01.771517 * Connection #0 to host localhost left intact
[{"id":1,"firstname":"John","Lastname":"Snow","status":"Learning things"},{"id":2,"firstname":"Daenerys","Lastname":"Targaryen","status":"Riding a dragon"}]
```
**Screenshots**
N/A
**Mockoon version:**
1.7.0
**OS / OS version:**
Ubuntu 18.04.4 LTS

**Comment by 255kb** [comment]
This seems linked to NodeJS timeout which is set to 2 minutes by default. 
https://stackoverflow.com/questions/21708208/express-js-response-timeout

**Comment by Eido95** [comment]
@255kb thank you for your input, does this bug have been fixed?

**Comment by 255kb** [comment]
@Eido95 It's fixed and will be released soon in v1.8.0. Expect it in the coming month. I still have some important things to add to this release.
